name: Build Artifacts

on:
  push:
    tags:
      - '*'

jobs:
  win-amd64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set env
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Setup GO
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.7'

    - name: Build
      run: CGO_ENABLED=0 GOARCH=amd64 GOOS=windows go build -a -installsuffix cgo -o ghmgr.exe .
    
    - name: Packing Arifact Files
      run: tar -zcvf ghmgr-${{ env.RELEASE_VERSION }}-win-amd64.tar.gz ghmgr.exe

    - name: Upload Artifact Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ github.workspace }}/ghmgr-${{ env.RELEASE_VERSION }}-win-amd64.tar.gz

  linux-amd64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set env
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Setup GO
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.7'

    - name: Build
      run: CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -a -installsuffix cgo -o ghmgr .
    
    - name: Packing Arifact Files
      run: tar -zcvf ghmgr-${{ env.RELEASE_VERSION }}-linux-amd64.tar.gz ghmgr

    - name: Upload Artifact Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ github.workspace }}/ghmgr-${{ env.RELEASE_VERSION }}-linux-amd64.tar.gz

  macOS-amd64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set env
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Setup GO
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.7'

    - name: Build
      run: CGO_ENABLED=0 GOARCH=amd64 GOOS=darwin go build -a -installsuffix cgo -o ghmgr .
    
    - name: Packing Arifact Files
      run: tar -zcvf ghmgr-${{ env.RELEASE_VERSION }}-macOS-amd64.tar.gz ghmgr

    - name: Upload Artifact Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ github.workspace }}/ghmgr-${{ env.RELEASE_VERSION }}-macOS-amd64.tar.gz

  macOS-arm64:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set env
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Setup GO
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.7'
    
    - name: Build
      run: CGO_ENABLED=0 GOARCH=arm64 GOOS=darwin go build -a -installsuffix cgo -o ghmgr .
    
    - name: Packing Arifact Files
      run: tar -zcvf ghmgr-${{ env.RELEASE_VERSION }}-macOS-arm64.tar.gz ghmgr

    - name: Upload Artifact Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ github.workspace }}/ghmgr-${{ env.RELEASE_VERSION }}-macOS-arm64.tar.gz


  
